data<-read.table("./household_power_consumption.txt",header=TRUE,sep=";",na.strings="?")
data[,"Date"]<-as.Date(data[,"Date"],format="%d/%m/%Y")
mydata<-subset(data,Date=="2007-02-01" | Date=="2007-02-02")
png(file="plot1.png",width=480,height=480)
hist(mydata$Global_active_power,col="red",main="Global Active Power",xlab="Global Active Power (kilowatts)")
dev.off()
read.csv.sql(r1,sql="select * from file where Date='16/12/2006'",sep=";")